.travis.yml, DEVEL.md, build-tools/python-tests.sh, build-tools/rel-build.sh, python/tests/test_bigipconfigdriver.py, python/tests/test_k8scloudbigip.py
Problem:
Repo needs CI that tests code, and pushes images to dockerhub.
Solution:
Added .travis.yml that builds and pushes an image to dockerhub that can be used for system tests and nightly regressions.
Note:
CI set up is being broken into two stages to simplify moving ongoing development. Created issue #12 for CI part 2.
=> Add travis CI part 1

.travis.yml, DEVEL.md, build-tools/python-tests.sh, build-tools/rel-build.sh, python/tests/test_bigipconfigdriver.py, python/tests/test_k8scloudbigip.py
* Add travis CI part 1
Problem:
Repo needs CI that tests code, and pushes images to dockerhub.
Solution:
Added .travis.yml that builds and pushes an image to dockerhub that can be used for system tests and nightly regressions.
Note:
CI set up is being broken into two stages to simplify moving ongoing development. Created issue #12 for CI part 2.
* fixup
(cherry picked from commit ca1da7817781da844bff385f30a49a3a18786dc8)
=> Add travis CI part 1 (#13)

f5router/bigipResources/bigipResources.go, f5router/f5router.go, f5router/f5router_test.go, testdata/resources/config0.json, testdata/resources/config1.json, testdata/resources/config2.json, testdata/resources/config3.json
Problem:
Wildcards routes were not resolved correctly for trailing or midstring
wildcards which would cause the BIG-IP to fail since it does not allow
for wildcard characters in policy rules.
Solution:
Add resolution for trailing and midstring wildcards for policy rules.
Fixes: #8
=> Fixed * resolution in policy rules.

README.md
Problem:
Coveralls badge pointed at "master" is showing coverage is "unavilaable".
Solution:
Use `?branch=HEAD` to indicate which number to post.
=> Fix coverage badge reference

f5router/bigipResources/bigipResources.go, f5router/f5router.go, f5router/tcpUpdate.go, testdata/resources/config0.json, testdata/resources/config1.json, testdata/resources/config2.json, testdata/resources/config3.json, testdata/resources/config4.json, testdata/resources/config5.json
Problem:
This bit is not being set which causes traffic to not flow as intended
Solution:
Update controller to set Source Address Translation to 'automap' on all
created virtuals
Update test configs to verify this is now set as expected
Fixes #25
=> Set Source Address Translation on virtuals

.travis.yml, build-tools/Dockerfile.builder, build-tools/build-release-images.sh
Problem:
- Dockerhub images did not have "latest" tag
- images need to be able to be specifically referenced in automated regression tests
Solution:
- Updated tagging to included latest.
- Added timestamp to build tag and included that information as a docker label to make it available to docker inspect in regression set up.
- Standardized whitespace in `Dockerfile.builder`
Fixes #22
=> Docker latest, Dockerfile.builder whitespace cleanup, pin image for systests

python/bigipconfigdriver.py, python/cf-build-requirements.txt, python/cf-runtime-requirements.txt, python/tests/test_cloudbigip.py
Moved code that configures vxlan tunnels and custom profiles via the f5-sdk
to CCCL and removed the dependency upon the f5-sdk and f5-icontrol-rest.
=> Remove f5-sdk dependency from CF ctlr

python/cf-build-requirements.txt, python/cf-runtime-requirements.txt
Incompatibility with policy rules fixed in f5-sdk 3.0.3, update
requirements to point to new CCCL version.
=> CCCL incompatible with BIG-IP v11.6.1 policies

docs/RELEASE-NOTES.rst, f5router/f5router.go, f5router/routeDomain.go, f5router/routeDomain_test.go, python/cf-build-requirements.txt, python/cf-runtime-requirements.txt
Problem:  Need to make sure controllers handle Big-IP addresses that
have optional route domain IDs specified.
Solution: Updating BindAddr processing to look for optional route
domains when processing the BindAddr field.
=> Added non-0 route domain support

build-tools/attributions-generator.sh
Problem:
travis build fails when running attributions-generator step
Solution:
Point travis to the proper docker registry (DockerHub) to get
the attributions-generator image from.
=> Use attributions-generator from DockerHub

docs/README.rst
Problem:
Users need to know which addresses cau use Big-IP route domains.
Solution:
Updated docs to indicate addresses that can have route domains and
added a link to the Big-IP documentation that explains route domains.
=> Updated documentation for route domain support

.travis.yml, Makefile, build-tools/_build-lib.sh, build-tools/build-debug-artifacts.sh, build-tools/build-release-artifacts.sh
Problem:
Build process was building images multiple times.
Solution:
Applied modificiations from https://github.com/F5Networks/k8s-bigip-ctlr/pull/355 as the same build scripts/patterns are used for both repos.
Fixes #28
=> remove redundant builds

.travis.yml, Makefile, build-tools/build-debug-artifacts.sh, build-tools/build-release-artifacts.sh
* remove redundant builds
Problem:
Build process was building images multiple times.
Solution:
Applied modificiations from https://github.com/F5Networks/k8s-bigip-ctlr/pull/355 as the same build scripts/patterns are used for both repos.
Fixes #28
* requested changes
(cherry picked from commit c3bdcab11b01e4dc68ab81ed42f30661066e5ed4)
=> remove redundant builds (#50)

config/config.go, config/config_test.go, f5router/bigipResources/JsessionidIRule.go, f5router/bigipResources/bigipResources.go, f5router/f5router.go, f5router/f5router_test.go, f5router/tcpUpdate.go, testdata/resources/config0.json, testdata/resources/config1.json, testdata/resources/config2.json
Problem:
Current controller could not configure JSESSIONID session persistence
on the BIG-IP.
Solution:
Add optional opt out JSESSIONID session persistence BIG-IP
configuration the same way that it is done in cloud foundry go router.
=> Added session persistence changes.

docs/README.rst, docs/RELEASE-NOTES.rst, f5router/bigipResources/JsessionidIRule.go
Problem:
Even though you can get a cookies value by [HTTP:cookie <name>] this
causes TCL warnings to be printed in the logs.
Solution:
Change [HTTP:cookie <name>] to [HTTP:cookie value <name>] to squash
warnings and also set a local variable with this lookup value so we do
not have to keep looking up this cookie's value everytime we need it.
=> Updated session persistence iRule.

config/config.go, config/config_test.go, f5router/bigipResources/bigipResources.go, f5router/f5router.go, f5router/httpUpdate.go, f5router/tcpUpdate.go, python/cf-build-requirements.txt, python/cf-runtime-requirements.txt, python/tests/test_cloudbigip.py, testdata/resources/config0.json, testdata/resources/config1.json, testdata/resources/config2.json, testdata/resources/config3.json, testdata/resources/config4.json, testdata/resources/config5.json, testdata/resources/config6.json
Problem:
The current config is missing properties that cccl is using as a
comparison which causes constant vs rewrites on the BIG-IP
Solution:
Add partition to object references
Add context to profiles
Add tcp profile to all vs
Update cccl pointer to pull in irule whitespace fix
Update test configs to verify output
Update default log level to "info" to match other controllers
Closes #72
=> Update config output to match cccl expectations

f5router/bigipResources/bigipResources.go, schema/cf-schema_v1.1.0.json
Problem:
Current schema and objects for custom health monitors lacked support
for receive strings like in the k8s-bigip-ctlr.
Solution:
Add support for receive strings.
=> Added receive strings to custom health monitors.

docs/README.rst, docs/RELEASE-NOTES.rst, docs/_static/config_examples/example-manifest.yml, docs/conf.py
Problem:
Current documentation does not cover per route configuration features.
Solution:
Add documentation that covers this feature.
=> Per route config docs.

docs/RELEASE-NOTES.rst
Added a bug fix note for a comparison problem in CCCL that caused
unnecessary updates to occur for Virtual Servers on BIG-IP
=> Release Notes for CCCL Virtual Server bug fix

.travis.yml
Problem:
Travis script uses variable CTLR_VERSION to set version
string when deploying docs. This variable is not being set.
Solution:
Added variable CTLR_VERSION to travis.
=> Added variable CTLR_VERSION to travis script

build-tools/docker-docs.sh, docs/Makefile
Problem:
The docs version string as displayed on the clouddocs sidebar for
product docs shows an incorrect version string.
Solution:
The problem is that the docs version string is based on the version
information from next-version.txt. This is okay for non-release branches
such as master but not accurate for the stable branches off of which we
pull releases.
The fix is to use the latest git tag to determine docs version for
stable branches.
=> Fix version information in documentation

python/bigipconfigdriver.py, python/tests/test_bigipconfigdriver.py
Problem
-The bigipconfigdriver.py crashed during certain startup errors that
are recoverable.
-The bigipconfigdriver.py was once again out of sync with the k8s
bigipconfigdriver.py.
Solution:
-Add retry backoff callbacks for recoverable startup errors.
- Bring bigipconfigdriver.py back into sync with k8s version.
Fixes: #113
=> Added startup retry callbacks.

docs/RELEASE-NOTES.rst, python/cf-build-requirements.txt, python/cf-runtime-requirements.txt
Problem: The CCCL library currently pulls in the f5-icontrol-rest
via the f5-common-python package.  This package does not pin the
f5-icontrol-rest package and new builds will therefore pull the
latest version.
Solution: Updated CCCL to pin the f5-icontrol-rest to a previous
version that did not have a memory leak issue.
=> Update CCCL pointer to a version that contains a stable f5-icontrol-rest

config/config.go, docs/README.rst, f5router/f5router.go
Problem:
The tier2_ip_range config param was a mandatory param which broker
backwards compatibility.
Solution:
Make tier2_ip_range optional with a sane default of 172.0.0.1/24 so it
does not need to be required.
Fixes: #127
=> Made tier2_ip_range optional.

.approvals.json, Makefile
Problem: There was no automated way to validate if all attributed packages have been approved by LRB.
Solution: The added license approvals file is now used by Attributions Generator to implement the audit check at build time.
=> Add license approvals file to support automation of audit check at build time.

docs/README.rst
Problem:
The language used to describe IP range for tier2 vips was a bit
confusing.
Solution:
Clarify that the above feature is "used" in Service Broker mode
only, not "required".
Fixes: #135
=> Clarify tier2_ip_range description

docs/RELEASE-NOTES.rst, f5router/f5router.go
Problem: Go vet reported a lock being passed by copy.
Solution: Remove copying of lock and pass by pointer.
Fixes #150
=> Fix govet errors in f5router.go

docs/RELEASE-NOTES.rst, f5router/f5router.go, f5router/f5router_test.go
Problem: The tier2_ip_range config parameter is only validated as being
a properly formatted CIDR block. However, it can be very easy as a user
to misconfigure this parameter causing errors on the BIG-IP creation of
tier2 VIPs. Prefixes should be evaluated to see if they fall on CIDR
block boundaries when users a trying to define networks with their
tier2_ip_range.
Solution: Added validation function and tests
Fixes #134
=> tier2_ip_range needs more robust validation

requirements.txt
CCCL incorrectly tried to get the length of a Nonetype. Metadata is a new addition to this version, so if upgrading controller versions, CCCL would hit this nonetype and throw an exception. CCCL now properly compares empty lists rather than Nonetypes.
=> Update CCCL pointer for metadata bug
